[tools]
node = "24.6.0"

[tasks.create-article]
description = "Create new article"
run = "npx zenn new:article"

[tasks.preview]
description = "Host article preview"
run = "npx zenn preview"

[tasks.publish]
description = "Publish article"
run = """
git add articles/
new_articles=`git diff --cached --name-only --diff-filter=ACMR articles/* | xargs -n1`
slugs=`git diff --cached --name-only --diff-filter=ACMR articles/* | xargs basename -s .md | xargs | tr ' ' ','`

if [[ -z "$new_articles" ]]; then
    echo "No publish targets found."
    exit 0
fi

echo "publish target:"
echo "$new_articles" | while read -r line; do 
    echo "\t- $line" 
done

read -r -p "\nPublish? [y/N](default: y): " ans
if [[ -z "$ans" || "$ans" =~ ^[Yy]$ ]]; then
    git commit -m \"publish: article(slug: $slugs)\"
    echo "✅ Published."
else
    echo "Unpablishd."
fi
"""

